# Generated by Django 4.2.25 on 2025-11-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_coupon_created_by_coupon_max_uses_per_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='max_uses_per_user',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
