# Generated by Django 4.2.25 on 2025-10-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
